### ISSUE TITLE
requests.exceptions.ConnectionError: HTTPConnectionPool(host='localhost', port=8097): Max retries exceeded with url: /update (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000020D0886A4F0>: Failed to est ablish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。'))

### ISSUE THREAD

**Issue by llyyccccc** [wdhudiekou/UMF-CMGR#50]
请问这个报错怎么解决呢？影响训练吗？
Traceback (most recent call last):
  File "D:\Anaconda\envs\faster_rcnn\lib\site-packages\visdom\__init__.py", line 756, in _send
    return self._handle_post(
  File "D:\Anaconda\envs\faster_rcnn\lib\site-packages\visdom\__init__.py", line 720, in _handle_post
    r = self.session.post(url, data=data)
  File "D:\Anaconda\envs\faster_rcnn\lib\site-packages\requests\sessions.py", line 635, in post
    return self.request("POST", url, data=data, json=json, **kwargs)
  File "D:\Anaconda\envs\faster_rcnn\lib\site-packages\requests\sessions.py", line 587, in request
    resp = self.send(prep, **send_kwargs)
  File "D:\Anaconda\envs\faster_rcnn\lib\site-packages\requests\sessions.py", line 701, in send
    r = adapter.send(request, **kwargs)
  File "D:\Anaconda\envs\faster_rcnn\lib\site-packages\requests\adapters.py", line 565, in send
    raise ConnectionError(e, request=request)
requests.exceptions.ConnectionError: HTTPConnectionPool(host='localhost', port=8097): Max retries exceeded with url: /update (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000020D05002640>: Failed to est
ablish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。'))
Epoch=6, lr=0.001
Exception in user code:
------------------------------------------------------------
Traceback (most recent call last):
  File "D:\Anaconda\envs\faster_rcnn\lib\site-packages\urllib3\connection.py", line 174, in _new_conn
    conn = connection.create_connection(
  File "D:\Anaconda\envs\faster_rcnn\lib\site-packages\urllib3\util\connection.py", line 95, in create_connection
    raise err
  File "D:\Anaconda\envs\faster_rcnn\lib\site-packages\urllib3\util\connection.py", line 85, in create_connection
    sock.connect(sa)
ConnectionRefusedError: [WinError 10061] 由于目标计算机积极拒绝，无法连接。

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\Anaconda\envs\faster_rcnn\lib\site-packages\urllib3\connectionpool.py", line 715, in urlopen
    httplib_response = self._make_request(
  File "D:\Anaconda\envs\faster_rcnn\lib\site-packages\urllib3\connectionpool.py", line 416, in _make_request
    conn.request(method, url, **httplib_request_kw)
  File "D:\Anaconda\envs\faster_rcnn\lib\site-packages\urllib3\connection.py", line 244, in request
    super(HTTPConnection, self).request(method, url, body=body, headers=headers)
  File "D:\Anaconda\envs\faster_rcnn\lib\http\client.py", line 1256, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "D:\Anaconda\envs\faster_rcnn\lib\http\client.py", line 1302, in _send_request
    self.endheaders(body, encode_chunked=encode_chunked)
  File "D:\Anaconda\envs\faster_rcnn\lib\http\client.py", line 1251, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "D:\Anaconda\envs\faster_rcnn\lib\http\client.py", line 1011, in _send_output
    self.send(msg)
  File "D:\Anaconda\envs\faster_rcnn\lib\http\client.py", line 951, in send
    self.connect()
  File "D:\Anaconda\envs\faster_rcnn\lib\site-packages\urllib3\connection.py", line 205, in connect
    conn = self._new_conn()
  File "D:\Anaconda\envs\faster_rcnn\lib\site-packages\urllib3\connection.py", line 186, in _new_conn
    raise NewConnectionError(
urllib3.exceptions.NewConnectionError: <urllib3.connection.HTTPConnection object at 0x0000020D088482B0>: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\Anaconda\envs\faster_rcnn\lib\site-packages\requests\adapters.py", line 489, in send
    resp = conn.urlopen(
  File "D:\Anaconda\envs\faster_rcnn\lib\site-packages\urllib3\connectionpool.py", line 799, in urlopen
    retries = retries.increment(
  File "D:\Anaconda\envs\faster_rcnn\lib\site-packages\urllib3\util\retry.py", line 592, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='localhost', port=8097): Max retries exceeded with url: /update (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000020D088482B0>: Failed to establ
ish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\Anaconda\envs\faster_rcnn\lib\site-packages\visdom\__init__.py", line 756, in _send
    return self._handle_post(
  File "D:\Anaconda\envs\faster_rcnn\lib\site-packages\visdom\__init__.py", line 720, in _handle_post
    r = self.session.post(url, data=data)
  File "D:\Anaconda\envs\faster_rcnn\lib\site-packages\requests\sessions.py", line 635, in post
    return self.request("POST", url, data=data, json=json, **kwargs)
  File "D:\Anaconda\envs\faster_rcnn\lib\site-packages\requests\sessions.py", line 587, in request
    resp = self.send(prep, **send_kwargs)
  File "D:\Anaconda\envs\faster_rcnn\lib\site-packages\requests\sessions.py", line 701, in send
    r = adapter.send(request, **kwargs)
  File "D:\Anaconda\envs\faster_rcnn\lib\site-packages\requests\adapters.py", line 565, in send
    raise ConnectionError(e, request=request)
requests.exceptions.ConnectionError: HTTPConnectionPool(host='localhost', port=8

**Comment by wdhudiekou** [comment]
安装visdom可以在线显示训练过程，当然也可以将visdom相关的代码都删掉就不会报错了。

**Comment by llyyccccc** [comment]
感谢大佬回复，我还想问一下使用自己训练权重报错
File "E:\UMF-CMGR-main\models\deformable_net.py", line 74, in load_state_dict
    del state_dict['net']['spatial_transform.grid']
KeyError: 'spatial_transform.grid'
是我的预训练权重有问题吗？ 还是我训练因为上面的报错有问题呢？ 期待您的回复

**Comment by wdhudiekou** [comment]
应该是kornia版本的问题
